package com.benyovszki.szakdolgozat.exception;

public enum ErrorType {
    ACCESS_DENIED,
    EMAIL_DOES_NOT_EXISTS,
    USERNAME_TAKEN,
    MODIFY_GLOBAL_TYPE,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_IN_USE,
    MISSING_OR_INCOMPLETE_PARAMETER,
    NO_USER_WITH_THIS_USERNAME,
    USER_ALREADY_EXISTS,
    ROLE_ALREADY_ADDED,
    ENTITY_NOT_FOUND,
    YOU_DONT_OWN_THIS_ENTITY,
}
